"""add specimen phase1 columns

Revision ID: 12f86fd4dbce
Revises: 94612ba135fb
Create Date: 2026-06-08 20:06:05.829706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f86fd4dbce'
down_revision: Union[str, Sequence[str], None] = '94612ba135fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen_informations', sa.Column('md5', sa.String(length=32), nullable=True))
    op.add_column('specimen_informations', sa.Column('sha1', sa.String(length=40), nullable=True))
    op.add_column('specimen_informations', sa.Column('crc32', sa.String(length=8), nullable=True))
    op.add_column('specimen_informations', sa.Column('ssdeep', sa.String(), nullable=True))
    op.add_column('specimen_informations', sa.Column('tlsh', sa.String(length=72), nullable=True))
    op.add_column('specimen_informations', sa.Column('type_detection', sa.JSON(), nullable=True))
    op.add_column('specimen_informations', sa.Column('detail_data', sa.JSON(), nullable=True))
    op.add_column('specimen_informations', sa.Column('has_detail_data', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('specimen_informations', sa.Column('last_analyze_log_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen_informations', 'last_analyze_log_data')
    op.drop_column('specimen_informations', 'has_detail_data')
    op.drop_column('specimen_informations', 'detail_data')
    op.drop_column('specimen_informations', 'type_detection')
    op.drop_column('specimen_informations', 'tlsh')
    op.drop_column('specimen_informations', 'ssdeep')
    op.drop_column('specimen_informations', 'crc32')
    op.drop_column('specimen_informations', 'sha1')
    op.drop_column('specimen_informations', 'md5')
    # ### end Alembic commands ###
