"""initial schema

Revision ID: 94612ba135fb
Revises: 
Create Date: 2026-06-08 02:22:09.131131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94612ba135fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_reception_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_reception_id')
    )
    op.create_table('specimen_informations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('analysis_state', sa.String(length=16), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('analysis_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_item_id', sa.String(length=32), nullable=False),
    sa.Column('request_reception_id', sa.String(length=32), nullable=False),
    sa.Column('parent_request_item_id', sa.String(length=32), nullable=True),
    sa.Column('register_type', sa.String(length=16), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('process_state', sa.String(length=16), nullable=False),
    sa.Column('current_phase', sa.String(length=64), nullable=True),
    sa.Column('error_type', sa.String(length=32), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_request_item_id'], ['analysis_request_items.request_item_id'], ),
    sa.ForeignKeyConstraint(['request_reception_id'], ['analysis_requests.request_reception_id'], ),
    sa.ForeignKeyConstraint(['sha256'], ['specimen_informations.sha256'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_item_id')
    )
    with op.batch_alter_table('analysis_request_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_request_items_process_state'), ['process_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_request_items_request_reception_id'), ['request_reception_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_request_items_sha256'), ['sha256'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_item_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['request_item_id'], ['analysis_request_items.request_item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_request_item_id'), ['request_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_request_item_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('analysis_request_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_request_items_sha256'))
        batch_op.drop_index(batch_op.f('ix_analysis_request_items_request_reception_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_request_items_process_state'))

    op.drop_table('analysis_request_items')
    op.drop_table('specimen_informations')
    op.drop_table('analysis_requests')
    # ### end Alembic commands ###
